// http://corewar.co.uk/standards/icws88.txt
// icws'88 syntax only, no '94+
// no labels, no vars (EQU) (sorry, too expensive)
// env variables not present (100b)
// no save/restore through hash (300b)
// more restrictions on input code (regex shortcuts)
// ops must be upper cased
// value normalization could break with high negatives
f(b,eval);

function f(
  b, P, X, Y,
  A, B, C, D, E,
  
  AA, AAA, AAAA, AAAAA, AAAAAA,
  AAAAAAA, AAAAAAAA, AAAAAAAA, AAAAAAAAA, AAAAAAAAA, AAAAAAAAAA, AAAAAAAAAAA,
  AAAAAAAAAAAA,
  AAAAAAAAAAAAA, AAAAAAAAAAAAAA, AAAAAAAAAAAAAAA, AAAAAAAAAAAAAAAA,
  AAAAAAAAAAAAAAAAA,
  AAAAAAAAAAAAAAAAAA, AAAAAAAAAAAAAAAAAAA,
  AAAAAAAAAAAAAAAAAAAA,
  AAAAAAAAAAAAAAAAAAAAA
) {
b.innerHTML = `<textarea id=W>
JMP   2    0
DAT   0    0
ADD   #2   -1
CMP   #2   -2
DAT   0    0
DJN   2    -4
DAT   0    0
DJN   -1   -6
JMP   3    0
DAT   0    0
DAT   0    1
JMN   2    -1
DAT   0    0
JMN   -1   -4
JMZ   2    -5
DAT   0    0
JMZ   -1   -6
MOV   7    1
DAT   8    9
SLT   -9   -10
SUB   #1   9
SPL   4    0
MOV   #0   -21
JMP   -21  0
JMP   1    0
MOV   4    <4
SUB   #4   3
ADD   #-6  3
ADD   2    1
DAT   0    -28
DAT   0    -1
</textarea><textarea id=Y>MOV 0 1</textarea><pre id=P></pre>`;
AAAAAAAAAAAAAA=n=>(n+8e9)%8e3;AAAAAAAAAAAAAAA=(X,Y,Z)=>Y=='#'?Z:X+Z+(Y?AAAAAAAAAAAAAAAA(X+Z)[4]-=Y=='<':0);AAAAAAAAAAAAAAAA=n=>AAA[AAAAAAAAAAAAAA(n)];AAAAAAAAAAAAA=(a,b,d=AAAAAAAAAAAAAAAAAAA=AAAAAAAAAAAAAAAAAA=0)=>a.value.replace(/^(.{3})(?: +([#@<]?) *([^,\s;]*)(?:[ ,]+([#@<]?) *([^,\s;]*))?)? *(;.*)?$/gm,(m,A,B='',C,D='',E)=>AAAAAAAAAAAAAAAAAAA||A&&(AAAAAAAAAAAAAAAAAAA=A=='END')?AAAAAAAAAAAAAAAAAA=C|0:AAA[AAAAAAAAAAAAAA(b+d++)]=[A,B,C|0,D,E|0])|AAAAAAAAAAAAAAAAAA;_=DAT=_=>AAAAAAAA=-1;ADD=(x,_=1)=>AAAAAAAAAAA[4]=AAAAAAAAA?AAAAAAAAAAA[4]+AAAAAAAA*_:(AAAAAAAAAAA[2]=AAAAAAAAAA[2]+AAAAAAAAAAA[2]*_,AAAAAAAAAA[4]+AAAAAAAAAAA[4]*_);SUB=_=>ADD(_,-1);CMP=_=>AAAAAAAA+=AAAAAAAAA?AAAAAAAA==AAAAAAAAAAA[4]:AAAAAAAAAA+''==AAAAAAAAAAA;DJN=_=>AAAAAAAA=--(D=='#'?AAAAAAAAAAAA:AAAAAAAAAAA)[4]?_:AAAAAAAA;JMP=_=>AAAAAAAA=_;JMN=_=>AAAAAAAA=AAAAAAAAAAA[4]?_:AAAAAAAA;JMZ=_=>AAAAAAAA=AAAAAAAAAAA[4]?AAAAAAAA:_;MOV=_=>AAAAAAAAA?AAAAAAAAAAA[4]=AAAAAAAA:AAA[AAAAAAAAAAAAAA(AAAAAAAAA)]=[...AAAAAAAAAA];SLT=_=>AAAAAAAA+=(AAAAAAAAA?AAAAAAAA:AAAAAAAAAA[4])<AAAAAAAAAAA[4];SPL=_=>AAAAAAAA=AAAAAAA.push(AAAAAAAAAAAAAA(++AAAAAAAA))&&_;(P.onclick=_=>(AAAAAAAAAAAAAAAAAAAAA=_=>{AAAAAAA=AAAAAAAAAAAAAAAAA%2?AAAA:AAAAAA;AAAAAAAA=AAAAAAA.shift();[A,B,C,D,E]=AAAAAAAAAAAA=AAAAAAAAAAAAAAAA(AAAAAAAA);AAAAAAAA=AAAAAAAAAAAAAAA(AAAAAAAA,B,C);AAAAAAAAA=AAAAAAAAAAAAAAA(AAAAAAAA,D,E);AAAAAAAAA=B=='#';AAAAAAAAAA=AAAAAAAAAAAAAAAA(AAAAAAAA);AAAAAAAAAAA=AAAAAAAAAAAAAAAA(AAAAAAAAA);eval(A)(AAAAAAAA-1);AAAAAAAA>=0&&SPL();P.innerHTML=AAA.map((A,i)=>(i%150?'':'\n')+(AAAA.includes(i)?`<b style='background-color:#109'>${A[0][0]}</b>`:AAAAAA.includes(i)?`<b style='background-color:#900'>${A[0][0]}</b>`:A[0][0])).join('')+(AAAAAAA.length ?--AAAAAAAAAAAAAAAAA?setTimeout(AAAAAAAAAAAAAAAAAAAAA,1)&&`${AAAAAAAAAAAAAAAAA} ${AAAA.length} `+AAAAAA.length:'Timeout':AAAAAAAAAAAAAAAAA%2?'B wins':'A wins')})(clearTimeout(AAAAAAAAAAAAAAAAAAAA),AAA=Array(8e3).fill(AAAAAAAAAAAAAAAAA=8e4).map(_=>'_#0#0'.split('')),AAAA=[AAAAAAAAAAAAA(W,0)],AAAAAA=[AAAAAAAAAAAAA(Y,AAAAA=100+~~(Math.random()*7800))+AAAAA]))()
}

